server:
  port: 8084
  servlet:
    context-path: /order_db
spring:
  datasource:
    url: ${DB_URL:}
    username: ${DB_USER:}
    password: ${DB_PASS:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true