server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
#            allowedOrigins:
#              - "http://localhost:5173"
#              - "http://127.0.0.1:5173"
#              - "http://localhost:3000"
#              - "http://127.0.0.1:3000"
#              - "http://localhost:5184"
#              - "http://127.0.0.1:5184"
            allowedOriginPatterns:
              - "http://localhost:*"
              - "http://127.0.0.1:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: identity-auth
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**

        - id: identity-users
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**

        - id: identity-address
          uri: http://localhost:8082
          predicates:
            - Path=/api/address/**

        - id: identity-verify
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/verify/**

        - id: notification-auth
          uri: http://localhost:8083
          predicates:
            - Path=/api/notifications/**

        - id: cloud-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/cloud/**

        - id: product-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/product/**

        - id: product-variant
          uri: http://localhost:8086
          predicates:
            - Path=/api/productVariant/**

        - id: product-reservations
          uri: http://localhost:8086
          predicates:
            - Path=/api/reservations/**

        - id: cart-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/cart/**

        - id: category-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/categories/**

        - id: revenue-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/dashboard/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.anta.filter: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers,gateway
  endpoint:
    gateway:
      enabled: true
